// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYzH6BkA3LbR3MPflsMdFMyiTiURmdhc',
    appId: '1:184860806950:web:d85e0b68871410e0debbe7',
    messagingSenderId: '184860806950',
    projectId: 'auth-learn-c2b3d',
    authDomain: 'auth-learn-c2b3d.firebaseapp.com',
    storageBucket: 'auth-learn-c2b3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShsBlwJ_FhAqV5ITkPdhYJkO3tWVWNHY',
    appId: '1:184860806950:android:39350e671de21792debbe7',
    messagingSenderId: '184860806950',
    projectId: 'auth-learn-c2b3d',
    storageBucket: 'auth-learn-c2b3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEpxYPorOBCmye0KTEB3eEqHmd0qXNVQ',
    appId: '1:184860806950:ios:d995c1da6203bed6debbe7',
    messagingSenderId: '184860806950',
    projectId: 'auth-learn-c2b3d',
    storageBucket: 'auth-learn-c2b3d.appspot.com',
    iosClientId: '184860806950-n520ije65tkamhkfa9rtvcpnjn3urle9.apps.googleusercontent.com',
    iosBundleId: 'com.example.progressHub',
  );
}
